# Generated by Django 3.2 on 2022-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='rank',
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
