# Generated by Django 3.2 on 2022-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='reply',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
