# Generated by Django 3.2 on 2022-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userinteraction_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='associated_choice_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
