# Generated by Django 3.2 on 2022-05-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_userinteraction_associated_choice_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='user_choice',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
