# Generated by Django 3.2 on 2022-07-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_experience_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
